### ISSUE TITLE
What do shared_secret and identity_secret mean?

### ISSUE THREAD

**Issue by KaiserKatze** [scholtzm/steam-auto-confirmations#1]
In [config.example.json](https://github.com/scholtzm/steam-auto-confirmations/blob/master/config.example.json)

``` json
{
  "username": "XXX",
  "password": "XXX",
  "shared_secret": "XXX",
  "identity_secret": "XXX"
}
```

**Comment by scholtzm** [comment]
The escrow stuff is explained [here](https://www.reddit.com/r/SteamBot/comments/3udhkd/everything_related_to_escrow/).

> `shared_secret` - used to generate 2FA auth code for login process
> `identity_secret` - used to generate 2FA auth code for accepting trade offers
