### ISSUE TITLE
Script says 0 confirmations received but there are market requests to confirm

### ISSUE THREAD

**Issue by dogauzun** [scholtzm/steam-auto-confirmations#2]
I attached the log file generated when I run the index.js. Here is more info in case it is helpful.

- I can confirm requests manually with my phone.
- I used the script successfully many times before
- My smartphone gets a notification for steamguard when I run the script.

[log.txt](https://github.com/scholtzm/steam-auto-confirmations/files/689593/log.txt)

**Comment by scholtzm** [comment]
To be completely honest, I haven't used the script in a while and never for market confirmations. I'll have a look.

**Comment by dogauzun** [comment]
Solved the problem by turning off my phone before running the script by the way. Thanks for the response.

**Comment by scholtzm** [comment]
Yeah, seems like running multiple authenticators has some side effects (maybe caused by different `device_id`s).
