### ISSUE TITLE
Where i can get shared_secret and identity_secret

### ISSUE THREAD

**Issue by etomarat** [scholtzm/steam-auto-confirmations#3]
I run `nodoe index.js`, and get code in steam mob app. What next? 
Its just repeating:
```[INFO] [steamguard] Received request for SteamGuard code.
[INFO] [steamguard] Waiting 30 seconds before generating new SteamGuard code.
[INFO] Connected to Steam network. Logging in...
[INFO] [steamguard] Received request for SteamGuard code.
[INFO] [steamguard] Waiting 30 seconds before generating new SteamGuard code.```

**Comment by scholtzm** [comment]
As per README.md:

```
3. Rename config.example.json to config.json
4. Edit config.json
```

You can retrieve `identity_secret` and `shared_secret` either from your phone or by registering TFA device programatically.

**Comment by etomarat** [comment]
how i can do that? Where is identity_secret and shared_secret in phone or how i can regisre TFA device programatically?

**Comment by scholtzm** [comment]
From phone: I believe your device needs to be rooted/jailbroken. I'm not sure, you'd have to look up the guide on the internet. I believe you could also intercept HTTP requests.

Programatically: For example using [`node-steamcommunity`](https://github.com/DoctorMcKay/node-steamcommunity/wiki/SteamCommunity#enabletwofactorcallback).
